name: Verify

on: [push]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: borales/actions-yarn@v2.0.0
    - name: Build and test
      run: |
        yarn
        yarn lint
        yarn format:check
        yarn build
        yarn test
