name: Verify

on: [push]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: "8.x" # TODO: bump to 10 ASAP
    - name: Build and test
      run: |
        yarn
        yarn lint
        yarn format:check
        yarn build
        yarn test
